CREATE TABLE "chevaux_trotteur_francais" (
  "id_tf" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_tf" VARCHAR(50) UNIQUE NOT NULL,
  "sexe_tf" VARCHAR(10) NOT NULL,
  "couleur_tf" VARCHAR(50),
  "annee_naissance_tf" INT NOT NULL,
  "pere_tf" VARCHAR(50),
  "mere_tf" VARCHAR(50),
  "date_decee_tf" DATE,
  "naisseur_tf" VARCHAR(100),
  "lien_ifce_tf" VARCHAR(150)
);

CREATE TABLE "programmes_des_courses" (
  "id_programme" INT PRIMARY KEY NOT NULL,
  "date_programme" DATE
);

CREATE TABLE "reunion" (
  "id_reunion" VARCHAR(50) PRIMARY KEY,
  "id_programme" INT NOT NULL,
  "num_officiel" INT,
  "nature" VARCHAR(50),
  "code_hippodrome" VARCHAR(4),
  "libelle_court_hippodrome" VARCHAR(40),
  "libelle_long_hippodrome" VARCHAR(60),
  "code_pays" VARCHAR(4),
  "libelle_pays" VARCHAR(30),
  "audience" VARCHAR(15),
  "statut" VARCHAR(15),
  "disciplines_mere" VARCHAR(150),
  "specialite_1" VARCHAR(30),
  "specialite_2" VARCHAR(30),
  "specialite_3" VARCHAR(30),
  "specialite_4" VARCHAR(30),
  "meteo_nebulosite_code" VARCHAR,
  "meteo_nebulosite_Libelle_Court" VARCHAR,
  "meteo_nebulosite_Libelle_Long" VARCHAR,
  "meteo_temperature" VARCHAR,
  "meteo_force_vent" VARCHAR,
  "meteo_direction_vent" VARCHAR
);

CREATE TABLE "courses" (
  "id_course" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_reunion" VARCHAR(50) NOT NULL,
  "libelle" VARCHAR(75),
  "libelle_court" VARCHAR(30),
  "heure_depart" TIME,
  "parcours" VARCHAR(30),
  "distance" INT,
  "distance_unit" VARCHAR(30),
  "corde" VARCHAR(50),
  "discipline" VARCHAR(50),
  "specialite_1" VARCHAR(50),
  "specialite_2" VARCHAR(50),
  "condition_sexe" VARCHAR(50),
  "conditions" VARCHAR(3000),
  "statut" VARCHAR(75),
  "categorie_statut" VARCHAR(30),
  "duree_course" INT,
  "duree_course_en_minute" VARCHAR(30),
  "montant_prix" INT,
  "grand_prix_national_trot" BOOL,
  "nombre_declares_partants" INT,
  "montant_total_offert" INT,
  "premier" INT,
  "montant_offert_1er" INT,
  "deuxieme" INT,
  "montant_offert_2eme" INT,
  "troisieme" INT,
  "montant_offert_3eme" INT,
  "quatrieme" INT,
  "montant_offert_4eme" INT,
  "cinquieme" INT,
  "montant_offert_5eme" INT,
  "incidents_type" VARCHAR(100),
  "incidents_participants" VARCHAR(100)
);

CREATE TABLE "participations_aux_courses" (
  "id_participation" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_course" INT NOT NULL,
  "nom" VARCHAR(75),
  "numero_cheval" INT,
  "age" INT,
  "sexe" VARCHAR(30),
  "race" VARCHAR(50),
  "statut_au_depart" VARCHAR(20),
  "proprietaire" VARCHAR(50),
  "entraineur" VARCHAR(50),
  "driver" VARCHAR(50),
  "driverChange" BOOL,
  "code_robe" VARCHAR(4),
  "libelle_court_robe" VARCHAR(20),
  "libelle_long_robe" VARCHAR(100),
  "nombre_courses" INT,
  "nombre_victoires" INT,
  "nombre_places" INT,
  "nom_pere" VARCHAR(100),
  "nom_mere" VARCHAR(100),
  "place_dans_la_course" INT,
  "jument_pleine" BOOL,
  "engagement" BOOL,
  "supplement" INT,
  "handicap_distance" INT,
  "poids_condition_monte_change" BOOL,
  "temps_obtenu" INT,
  "temps_obtenu_en_minute" VARCHAR(50),
  "reduction_kilometrique" INT,
  "allure" VARCHAR(20)
);

ALTER TABLE "reunion" ADD FOREIGN KEY ("id_programme") REFERENCES "programmes_des_courses" ("id_programme");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_reunion") REFERENCES "reunion" ("id_reunion");

ALTER TABLE "participations_aux_courses" ADD FOREIGN KEY ("id_course") REFERENCES "courses" ("id_course");
