# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAnneedenaissance():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_anneedenaissance(self):
    self.driver.get("https://infochevaux.ifce.fr/fr/info-chevaux")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1) > .card-header").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1) > .card-header").click()
    self.driver.find_element(By.ID, "reproducteur-annee_naissance_cheval").click()
    self.driver.find_element(By.LINK_TEXT, "2024").click()
    self.driver.find_element(By.CSS_SELECTOR, "#reproducteur-race_cheval > .caret").click()
    self.driver.find_element(By.CSS_SELECTOR, "#reproducteur-race_cheval > .caret").click()
    self.driver.find_element(By.ID, "reproducteur-annee_naissance_cheval").click()
    self.driver.find_element(By.LINK_TEXT, "2024").click()
    element = self.driver.find_element(By.LINK_TEXT, "2024")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "reproducteur-annee_naissance_cheval").click()
    self.driver.find_element(By.LINK_TEXT, "2023").click()
    self.driver.find_element(By.ID, "reproducteur-annee_naissance_cheval").click()
    self.driver.find_element(By.LINK_TEXT, "2022").click()
    element = self.driver.find_element(By.LINK_TEXT, "2022")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "reproducteur-annee_naissance_cheval").click()
    self.driver.find_element(By.LINK_TEXT, "2019").click()
  
